import { InstrumentDefinition, MusicInstrument } from '../types';

export const INSTRUMENT_REGISTRY: Record<MusicInstrument, InstrumentDefinition> = {
  piano: {
    id: 'piano',
    name: 'Piano',
    category: 'keyboard',
    icon: '🎹',
    performerTitle: 'Pianist',
    defaultEnsembleRank: 1,
  },
  drums: {
    id: 'drums',
    name: 'Drums',
    category: 'percussion',
    icon: '🥁',
    performerTitle: 'Drummer',
    defaultEnsembleRank: 2,
  },
  bass: {
    id: 'bass',
    name: 'Bass Guitar',
    category: 'strings',
    icon: '🎸',
    performerTitle: 'Bassist',
    defaultEnsembleRank: 3,
  },
  'electric-guitar': {
    id: 'electric-guitar',
    name: 'Electric Guitar',
    category: 'strings',
    icon: '🎸',
    performerTitle: 'Lead Guitarist',
    defaultEnsembleRank: 4,
  },
  'acoustic-guitar': {
    id: 'acoustic-guitar',
    name: 'Acoustic Guitar',
    category: 'strings',
    icon: '🎸',
    performerTitle: 'Acoustic Guitarist',
    defaultEnsembleRank: 5,
  },
  violin: {
    id: 'violin',
    name: 'Violin',
    category: 'strings',
    icon: '🎻',
    performerTitle: 'Violinist',
    defaultEnsembleRank: 6,
  },
  cello: {
    id: 'cello',
    name: 'Cello',
    category: 'strings',
    icon: '🎻',
    performerTitle: 'Cellist',
    defaultEnsembleRank: 7,
  },
  flute: {
    id: 'flute',
    name: 'Flute',
    category: 'woodwind',
    icon: '🪈',
    performerTitle: 'Flutist',
    defaultEnsembleRank: 8,
  },
  saxophone: {
    id: 'saxophone',
    name: 'Saxophone',
    category: 'woodwind',
    icon: '🎷',
    performerTitle: 'Saxophonist',
    defaultEnsembleRank: 9,
  },
  trumpet: {
    id: 'trumpet',
    name: 'Trumpet',
    category: 'brass',
    icon: '🎺',
    performerTitle: 'Trumpeter',
    defaultEnsembleRank: 10,
  },
  vocalist: {
    id: 'vocalist',
    name: 'Vocalist',
    category: 'vocal',
    icon: '🎤',
    performerTitle: 'Vocalist',
    defaultEnsembleRank: 11,
  },
  'church-organ': {
    id: 'church-organ',
    name: 'Church Organ',
    category: 'keyboard',
    icon: '⛪',
    performerTitle: 'Organist',
    defaultEnsembleRank: 12,
  },
  synthesizer: {
    id: 'synthesizer',
    name: 'Synthesizer Workstation',
    category: 'electronic',
    icon: '🎛️',
    performerTitle: 'Synth Player',
    defaultEnsembleRank: 13,
  },
  'electronic-drums': {
    id: 'electronic-drums',
    name: 'Electronic Drum Kit',
    category: 'percussion',
    icon: '🥁',
    performerTitle: 'Electronic Drummer',
    defaultEnsembleRank: 14,
  },
  'dj-turntable': {
    id: 'dj-turntable',
    name: 'DJ Turntables & Mixer',
    category: 'electronic',
    icon: '🎧',
    performerTitle: 'DJ / Producer',
    defaultEnsembleRank: 15,
  },
  harp: {
    id: 'harp',
    name: 'Concert Harp',
    category: 'strings',
    icon: '🪕',
    performerTitle: 'Harpist',
    defaultEnsembleRank: 16,
  },
};

export const ALL_INSTRUMENTS: MusicInstrument[] = [
  'piano',
  'drums',
  'bass',
  'electric-guitar',
  'acoustic-guitar',
  'violin',
  'cello',
  'flute',
  'saxophone',
  'trumpet',
  'vocalist',
  'church-organ',
  'synthesizer',
  'electronic-drums',
  'dj-turntable',
  'harp',
];

export function getInstrumentDefinition(id: MusicInstrument): InstrumentDefinition {
  return INSTRUMENT_REGISTRY[id] || INSTRUMENT_REGISTRY.piano;
}
