import { InstrumentDefinition, MusicInstrument } from '../types';

export const INSTRUMENT_REGISTRY: Record<MusicInstrument, InstrumentDefinition> = {
  // ==========================================
  // ACOUSTIC / TRADITIONAL / ORCHESTRAL
  // ==========================================
  piano: {
    id: 'piano',
    name: 'Concert Grand Piano',
    category: 'keyboard',
    icon: '🎹',
    performerTitle: 'Pianist',
    description: 'Acoustic grand piano played seated with dynamic keys and expressive chords',
    defaultEnsembleRank: 1,
    performerType: 'seated',
    requiresSeatedPerformer: true,
    visualVariant: 'piano',
    aliases: ['grand piano', 'upright piano', 'acoustic piano', 'pianoforte'],
  },
  'acoustic-guitar': {
    id: 'acoustic-guitar',
    name: 'Acoustic Guitar',
    category: 'strings',
    icon: '🎸',
    performerTitle: 'Acoustic Guitarist',
    description: 'Steel-string acoustic guitar providing rhythmic strumming and resonant fingerstyle chords',
    defaultEnsembleRank: 4,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'acoustic-guitar',
    aliases: ['steel string guitar', 'folk guitar', 'acoustic'],
  },
  'classical-guitar': {
    id: 'classical-guitar',
    name: 'Classical Guitar',
    category: 'strings',
    icon: '🎸',
    performerTitle: 'Classical Guitarist',
    description: 'Nylon-string Spanish guitar played with delicate fingerstyle technique',
    defaultEnsembleRank: 5,
    performerType: 'seated',
    requiresSeatedPerformer: true,
    visualVariant: 'classical-guitar',
    aliases: ['spanish guitar', 'nylon guitar', 'flamenco guitar'],
  },
  'electric-guitar': {
    id: 'electric-guitar',
    name: 'Electric Guitar',
    category: 'strings',
    icon: '🎸',
    performerTitle: 'Lead Guitarist',
    description: 'Solid-body electric guitar delivering melodic solos, distortion, and rock riffs',
    defaultEnsembleRank: 6,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'electric-guitar',
    aliases: ['lead guitar', 'rhythm guitar', 'stratocaster', 'telecaster', 'les paul'],
  },
  bass: {
    id: 'bass',
    name: 'Bass Guitar',
    category: 'strings',
    icon: '🎸',
    performerTitle: 'Bassist',
    description: 'Electric 4-string bass locking in groove, root notes, and bottom-end punch',
    defaultEnsembleRank: 7,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'bass',
    aliases: ['electric bass', 'bass player', 'bassline'],
  },
  'double-bass': {
    id: 'double-bass',
    name: 'Double Bass / Upright Bass',
    category: 'strings',
    icon: '🎻',
    performerTitle: 'Double Bassist',
    description: 'Large wooden acoustic upright bass played upright with pizzicato or bow',
    defaultEnsembleRank: 8,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'double-bass',
    aliases: ['upright bass', 'contrabass', 'standup bass', 'string bass'],
  },
  violin: {
    id: 'violin',
    name: 'Violin',
    category: 'strings',
    icon: '🎻',
    performerTitle: 'Violinist',
    description: 'Soprano orchestral bowed string instrument producing soaring, virtuosic lead melodies',
    defaultEnsembleRank: 2,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'violin',
    aliases: ['fiddle', 'first violin', 'solo violin'],
    // 3D Miniature Model
    has3DModel: true,
    modelPath: '/music-lab/musicians/violinist.glb',
    idleAnimation: 'idle',
    playingAnimation: 'playing',
    scale3D: 1.0,
    position3D: [0, 0, 0],
  },
  viola: {
    id: 'viola',
    name: 'Viola',
    category: 'strings',
    icon: '🎻',
    performerTitle: 'Violist',
    description: 'Warm, alto-voiced string instrument filling rich inner harmonic textures',
    defaultEnsembleRank: 9,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'viola',
    aliases: ['alto violin', 'bratsche'],
  },
  cello: {
    id: 'cello',
    name: 'Cello',
    category: 'strings',
    icon: '🎻',
    performerTitle: 'Cellist',
    description: 'Tenor and bass bowed string instrument seated with endpin, rich resonance and heartfelt warmth',
    defaultEnsembleRank: 3,
    performerType: 'seated',
    requiresSeatedPerformer: true,
    visualVariant: 'cello',
    aliases: ['violoncello', 'solo cello', 'cello quartet'],
  },
  flute: {
    id: 'flute',
    name: 'Concert Flute',
    category: 'woodwind',
    icon: '🪈',
    performerTitle: 'Flutist',
    description: 'Transverse silver woodwind delivering airy, agile high-register melodies',
    defaultEnsembleRank: 12,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'flute',
    aliases: ['transverse flute', 'piccolo', 'silver flute'],
  },
  clarinet: {
    id: 'clarinet',
    name: 'Clarinet',
    category: 'woodwind',
    icon: '🎷',
    performerTitle: 'Clarinetist',
    description: 'Single-reed wooden instrument with a wide dynamic range from mellow chalumeau to bright clarion',
    defaultEnsembleRank: 13,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'clarinet',
    aliases: ['soprano clarinet', 'woodwind clarinet'],
  },
  oboe: {
    id: 'oboe',
    name: 'Oboe',
    category: 'woodwind',
    icon: '🪈',
    performerTitle: 'Oboist',
    description: 'Double-reed orchestral instrument known for penetrating, expressive, melancholic timbre',
    defaultEnsembleRank: 14,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'oboe',
    aliases: ['hautbois', 'cor anglais'],
  },
  bassoon: {
    id: 'bassoon',
    name: 'Bassoon',
    category: 'woodwind',
    icon: '🪈',
    performerTitle: 'Bassoonist',
    description: 'Large double-reed bass woodwind providing staccato basslines and reedy tenor character',
    defaultEnsembleRank: 15,
    performerType: 'seated',
    requiresSeatedPerformer: true,
    visualVariant: 'bassoon',
    aliases: ['fagotto', 'contrabassoon'],
  },
  saxophone: {
    id: 'saxophone',
    name: 'Saxophone',
    category: 'woodwind',
    icon: '🎷',
    performerTitle: 'Saxophonist',
    description: 'Curved brass instrument with reed mouthpiece for smooth jazz melodies and biting riffs',
    defaultEnsembleRank: 11,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'saxophone',
    aliases: ['alto sax', 'tenor sax', 'soprano sax', 'baritone sax'],
  },
  trumpet: {
    id: 'trumpet',
    name: 'Trumpet',
    category: 'brass',
    icon: '🎺',
    performerTitle: 'Trumpeter',
    description: 'High brass horn cutting through ensembles with fanfare brilliance and jazz swing',
    defaultEnsembleRank: 16,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'trumpet',
    aliases: ['cornet', 'flugelhorn', 'brass trumpet'],
  },
  trombone: {
    id: 'trombone',
    name: 'Trombone',
    category: 'brass',
    icon: '🎺',
    performerTitle: 'Trombonist',
    description: 'Slide-operated brass instrument delivering powerful brass glissandi and warm tenor chords',
    defaultEnsembleRank: 17,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'trombone',
    aliases: ['tenor trombone', 'bass trombone'],
  },
  'french-horn': {
    id: 'french-horn',
    name: 'French Horn',
    category: 'brass',
    icon: '📯',
    performerTitle: 'Hornist',
    description: 'Coiled brass instrument with bell facing backward, producing cinematic noble calls',
    defaultEnsembleRank: 18,
    performerType: 'seated',
    requiresSeatedPerformer: true,
    visualVariant: 'french-horn',
    aliases: ['cor d harmonie', 'orchestral horn'],
  },
  tuba: {
    id: 'tuba',
    name: 'Concert Tuba',
    category: 'brass',
    icon: '📯',
    performerTitle: 'Tubist',
    description: 'Largest brass instrument providing deepest acoustic foundation and orchestral weight',
    defaultEnsembleRank: 19,
    performerType: 'seated',
    requiresSeatedPerformer: true,
    visualVariant: 'tuba',
    aliases: ['bass tuba', 'sousaphone'],
  },
  harp: {
    id: 'harp',
    name: 'Concert Pedal Harp',
    category: 'strings',
    icon: '🪕',
    performerTitle: 'Harpist',
    description: 'Large triangular frame harp with plucked strings creating ethereal glissandi and arpeggios',
    defaultEnsembleRank: 20,
    performerType: 'seated',
    requiresSeatedPerformer: true,
    visualVariant: 'harp',
    aliases: ['pedal harp', 'celtic harp', 'orchestral harp'],
  },
  accordion: {
    id: 'accordion',
    name: 'Accordion',
    category: 'keyboard',
    icon: '🪗',
    performerTitle: 'Accordionist',
    description: 'Bellows-driven reed instrument with keys and chord buttons for lively folk and European themes',
    defaultEnsembleRank: 21,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'accordion',
    aliases: ['squeezebox', 'concertina', 'bayan'],
  },
  mandolin: {
    id: 'mandolin',
    name: 'Mandolin',
    category: 'strings',
    icon: '🪕',
    performerTitle: 'Mandolinist',
    description: 'Paired eight-string lute-family instrument played with rapid tremolo picking',
    defaultEnsembleRank: 22,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'mandolin',
    aliases: ['bluegrass mandolin', 'italian mandolin'],
  },
  'church-organ': {
    id: 'church-organ',
    name: 'Church Organ',
    category: 'keyboard',
    icon: '⛪',
    performerTitle: 'Church Organist',
    description: 'Sacred multi-manual keyboard console with pedals filling cathedrals with majestic sound',
    defaultEnsembleRank: 23,
    performerType: 'seated',
    requiresSeatedPerformer: true,
    visualVariant: 'church-organ',
    aliases: ['cathedral organ', 'chapel organ', 'sacred organ'],
  },
  'pipe-organ': {
    id: 'pipe-organ',
    name: 'Grand Concert Pipe Organ',
    category: 'keyboard',
    icon: '🏛️',
    performerTitle: 'Pipe Organist',
    description: 'Massive concert hall pipe installation with rows of gleaming architectural pipes and console',
    defaultEnsembleRank: 24,
    performerType: 'seated',
    requiresSeatedPerformer: true,
    visualVariant: 'pipe-organ',
    aliases: ['symphonic pipe organ', 'auditorium organ'],
  },
  timpani: {
    id: 'timpani',
    name: 'Timpani / Kettle Drums',
    category: 'percussion',
    icon: '🥁',
    performerTitle: 'Timpanist',
    description: 'Tuned copper kettle drums struck with soft mallets for dramatic orchestral thunder and climaxes',
    defaultEnsembleRank: 25,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'timpani',
    aliases: ['kettledrums', 'orchestral kettles'],
  },
  percussion: {
    id: 'percussion',
    name: 'Orchestral Percussion',
    category: 'percussion',
    icon: '🔔',
    performerTitle: 'Percussionist',
    description: 'Auxiliary orchestral percussion including cymbals, triangle, tambourine, and orchestral chimes',
    defaultEnsembleRank: 26,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'percussion',
    aliases: ['auxiliary percussion', 'chimes', 'shakers', 'xylophone', 'marimba'],
  },
  drums: {
    id: 'drums',
    name: 'Acoustic Drum Kit',
    category: 'percussion',
    icon: '🥁',
    performerTitle: 'Drummer',
    description: 'Full acoustic drum kit with bass drum, snare, toms, hi-hats, and cymbals driving the beat',
    defaultEnsembleRank: 10,
    performerType: 'seated',
    requiresSeatedPerformer: true,
    visualVariant: 'drums',
    aliases: ['drum set', 'trap kit', 'acoustic drums'],
  },

  // ==========================================
  // VOICE / ENSEMBLE
  // ==========================================
  vocalist: {
    id: 'vocalist',
    name: 'Lead Vocalist',
    category: 'vocal',
    icon: '🎤',
    performerTitle: 'Lead Singer',
    description: 'Solo human singing voice performing lead vocal melodies at the microphone',
    defaultEnsembleRank: 0,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'vocalist',
    aliases: ['singer', 'lead vocals', 'vocal solo', 'frontman', 'frontwoman'],
  },
  'vocals-effects': {
    id: 'vocals-effects',
    name: 'Vocals + FX / Vocoder',
    category: 'vocal',
    icon: '🎙️',
    performerTitle: 'Vocal Effect Performer',
    description: 'Processed vocals, autotune, vocoder, and electronic vocal harmonization effects',
    defaultEnsembleRank: 27,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'vocals-effects',
    aliases: ['autotune vocals', 'vocoder', 'pitch-shifted voice', 'vocal chops'],
  },
  choir: {
    id: 'choir',
    name: 'Vocal Choir Ensemble',
    category: 'vocal',
    icon: '👥',
    performerTitle: 'Choir Group',
    description: 'Multi-part vocal choral ensemble producing lush backing harmonies and epic chants',
    defaultEnsembleRank: 28,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'choir',
    aliases: ['chorus', 'backing vocalists', 'gospel choir', 'chamber choir'],
  },

  // ==========================================
  // ELECTRONIC / MODERN / PRODUCTION
  // ==========================================
  synthesizer: {
    id: 'synthesizer',
    name: 'Analog Synthesizer',
    category: 'electronic',
    icon: '🎛️',
    performerTitle: 'Synthesist',
    description: 'Electronic synthesizer keyboard with knobs, filters, arpeggiators, and lead patches',
    defaultEnsembleRank: 29,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'synthesizer',
    aliases: ['analog synth', 'modular synth', 'moog', 'synth lead'],
  },
  'keyboard-workstation': {
    id: 'keyboard-workstation',
    name: 'Keyboard Workstation',
    category: 'electronic',
    icon: '🎹',
    performerTitle: 'Keyboardist',
    description: 'Digital electronic stage piano workstation with split layers, pads, and organ patches',
    defaultEnsembleRank: 30,
    performerType: 'seated',
    requiresSeatedPerformer: true,
    visualVariant: 'keyboard-workstation',
    aliases: ['digital piano', 'stage keyboard', 'nord', 'roland workstation'],
  },
  'dj-turntable': {
    id: 'dj-turntable',
    name: 'DJ Turntables & Mixer',
    category: 'electronic',
    icon: '🎧',
    performerTitle: 'DJ / Turntablist',
    description: 'Dual vinyl turntables and DJ mixer performing vinyl scratching, beatmatching, and drops',
    defaultEnsembleRank: 31,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'dj-turntable',
    aliases: ['turntables', 'dj mixer', 'decks', 'scratching'],
  },
  sampler: {
    id: 'sampler',
    name: 'Audio Sampler (MPC)',
    category: 'electronic',
    icon: '🎚️',
    performerTitle: 'Sampler Performer',
    description: 'Hardware audio sampler triggering audio chops, vocal hooks, and sample loops',
    defaultEnsembleRank: 32,
    performerType: 'station',
    requiresStandingPerformer: true,
    visualVariant: 'sampler',
    aliases: ['mpc', 'sp404', 'sample trigger', 'pad sampler'],
  },
  'drum-machine': {
    id: 'drum-machine',
    name: 'Hardware Drum Machine',
    category: 'electronic',
    icon: '🎛️',
    performerTitle: 'Beat Programmer',
    description: 'Step-sequenced electronic analog drum synthesizer (808 / 909 beats)',
    defaultEnsembleRank: 33,
    performerType: 'station',
    requiresStandingPerformer: true,
    visualVariant: 'drum-machine',
    aliases: ['808', '909', 'beatbox hardware', 'groovebox'],
  },
  'electronic-drum-pad': {
    id: 'electronic-drum-pad',
    name: 'Electronic Drum Pad (Octapad)',
    category: 'percussion',
    icon: '🥁',
    performerTitle: 'Electronic Percussionist',
    description: 'Multi-pad digital percussion controller played with drumsticks for modern live beats',
    defaultEnsembleRank: 34,
    performerType: 'standing',
    requiresStandingPerformer: true,
    visualVariant: 'electronic-drum-pad',
    aliases: ['octapad', 'spdsx', 'multipads', 'percussion pad'],
  },
  'electronic-drums': {
    id: 'electronic-drums',
    name: 'Electronic Drum Kit (V-Drums)',
    category: 'percussion',
    icon: '🥁',
    performerTitle: 'V-Drums Drummer',
    description: 'Mesh-head digital electronic drum kit with cymbals and drum module',
    defaultEnsembleRank: 35,
    performerType: 'seated',
    requiresSeatedPerformer: true,
    visualVariant: 'drums',
    aliases: ['v-drums', 'electronic kit', 'roland drums'],
  },
  'midi-controller': {
    id: 'midi-controller',
    name: 'MIDI Pad & Fader Controller',
    category: 'electronic',
    icon: '🎚️',
    performerTitle: 'MIDI Controller Artist',
    description: 'Grid controller with faders and backlit pads launching clips and software parameters',
    defaultEnsembleRank: 36,
    performerType: 'station',
    requiresStandingPerformer: true,
    visualVariant: 'midi-controller',
    aliases: ['launchpad', 'push', 'midi grid', 'fader controller'],
  },
  sequencer: {
    id: 'sequencer',
    name: 'Analog Hardware Sequencer',
    category: 'electronic',
    icon: '🎛️',
    performerTitle: 'Step Sequencer Artist',
    description: 'Running hardware step sequencer driving rhythmic modulation and synth patterns',
    defaultEnsembleRank: 37,
    performerType: 'station',
    requiresStandingPerformer: true,
    visualVariant: 'sequencer',
    aliases: ['step sequencer', 'euclidean sequencer', 'cv gate'],
  },
  'electronic-producer': {
    id: 'electronic-producer',
    name: 'Live Electronic Producer',
    category: 'electronic',
    icon: '💻',
    performerTitle: 'Electronic Producer',
    description: 'Modern live electronic musician directing software synths, effects, and mixing console',
    defaultEnsembleRank: 38,
    performerType: 'station',
    requiresStandingPerformer: true,
    visualVariant: 'electronic-producer',
    aliases: ['live producer', 'daw performer', 'electronic live act'],
  },
};

export const ALL_INSTRUMENTS: MusicInstrument[] = Object.keys(
  INSTRUMENT_REGISTRY
) as MusicInstrument[];

export function getInstrumentDefinition(id: MusicInstrument): InstrumentDefinition {
  return INSTRUMENT_REGISTRY[id] || INSTRUMENT_REGISTRY.piano;
}

export function getMusician3DConfig(id: MusicInstrument) {
  const def = getInstrumentDefinition(id);
  if (def.has3DModel && def.modelPath) {
    return {
      instrumentId: id,
      modelPath: def.modelPath,
      idleAnimation: def.idleAnimation || 'idle',
      playingAnimation: def.playingAnimation || 'playing',
      scale: def.scale3D || 1.0,
      position: def.position3D || [0, 0, 0],
      rotation: def.rotation3D || [0, 0, 0],
    };
  }
  return null;
}
